name: music_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  english_words: ^4.0.0
  provider: ^6.1.2

  pluto_grid: ^8.0.0
  file_picker: ^10.1.4
  fancy_password_field: ^2.0.8
  firebase_core: ^3.13.0
  cloud_firestore: 5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
